travis:
  secure:
    BINSTAR_TOKEN: a9rb+6YB4vLb9sJOvzvkYisRxqevR6spOh306y6QtiWAoxz64GAT53MNVFfOayXhxDjWQBECaT0XTCaxrC25VwnzUp7BEizBtCwRHmJNuOStT2HFgHoFWQHq+iDcEuPCANrVWjo7Z/Q0bistCCZfUKa3qwPdTGyMbIWl8oHEUiatYauCp7sZvmwb5RLAUu5GtuuTdFoq94oUgNXhtXBAc7oMBvZSFFdYYznVHCEidWXzGQnTp4eLVQz5s3lkmRgivQuzDGCsoJgAPhFNnFs3x1X0Y1o8NLSiLQw+yxJrbXC3Dco9RnEfpnkZy7OEjNfikbBcwCbt9NXmR5EXEGX2iNCwmssyZV/kRZ3su4Je4IOUxXY4H88Am6vT0h+/X6cueUOBsd9DvyG7rTwfrUVdHB2pp/elEF6Kig6qoLW6P5ndsX5/NYAWX08W+krF2JgGsVwBX23gZ8r1QyAOtvtSy/JXAVv6EUO3QN/nudpDj9XKetp/FEuJ7NYthGqsNg43Ki0ghDqh/9u+CG9RmmhoTSAL4tSTV/ffnIU6Q9Cg2OsyRVj6Cef/6jXeNN5f75NOVyavi6rtujzmo9jSikLYvmBQFtWHQ7M9uR5yp6WfPJsUKCdkxrYU12Fu8hzHKftsQxga0LJibPxJkg/Q6n8VAYdX1HgW+wV7rOBzBUz9nI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
